---
- name: Config server and install apt
  hosts: all
  become: true
  tasks:
    - name: Disable swap # Отключаем swap, так как kubeadm не работает с включенным swap
      command: swapoff -a
      changed_when: false

    - name: Remove swap from fstab # Коментируем swap в fstab, чтобы он не включался при перезагрузке
      replace: # Модуль замены
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]*\sswap\s+sw\s+.*)$'
        replace: '# \1\2'
        backup: yes

    - name: Load kernel modules
      modprobe: # Модуль ядра для работы контейера
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl
      sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        reload: no
      loop:
        - net.bridge.bridge-nf-call-iptables # iptables может видеть трафик проходящий через мосты
        - net.bridge.bridge-nf-call-ip6tables # тоже самое для ipv6
        - net.ipv4.ip_forward # разрешает маршрутизацию пакетов между сетями

    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes # обновить список пакетов

    - name: Create containerd config directory
      file:
        path: /etc/containerd # Пака для конфигов не всегда создается
        state: directory

    - name: Generate default containred config
      shell: containerd config default > /etc/containerd/config.tolm
      args: # Создать если еще не создан
        creates: /etc/containerd/config.tolm

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Add k8s apt key
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        state: present

    - name: Add K8s repo
      apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        state: present
        update_cache: yes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present

    - name: Hold kubeadm, kubelet, kubectl # Отмена обновлений по команде
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubeadm
        - kubelet
        - kubectl

- name: Init k8s master
  hosts: master
  become: true
  tasks:
    - name: On IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Init cluster
      shell: |
        kubeadm init --pod-network-cidr=192.162.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf # Выполнять только если папка еще не создана

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to .kube # Это чтобы использовать Kubectl на master
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0644'

    - name: Install Calico CNI
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.32.1/manifests/calico.yaml
      args:
        creates: /root/.kube/calico-installed

    - name: Get token for workers
      shell: kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Save join_command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /root/join_command.sh
        mode: '0755'

    - name: Save join_command to host
      fetch:
        src: /root/join_command.sh
        dest: /tmp/join_command.sh
        flat: yes # Копирование без создания промежуточных папок

    - name: Fetch kubeconfig to host # Копируем чтобы пользоваться kubectl с собственного компа
      fetch:
        src: /root/.kube/config
        dest: ~/.kube/config-beget # после выполнения надо будет export KUBECONFIG=~/.kube/config-beget
        flat: yes
        mode: "0600"

- name: Init k8s workers
  hosts: workers
  become: true
  tasks:
    - name: On IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
      become: true

    - name: Copy join_command
      copy:
        src: /tmp/join_command.sh
        dest: /root/join_command.sh
        mode: '0755'

    - name: Execute join_command
      shell: /root/join_command.sh
      args:
        creates: /etc/kubernetes/kubelet.conf