apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base/frontend
  - ../../base/backend
  - ../../base/database
  - ../../base/ingress

patches:
  - target:
      kind: ConfigMap
      name: frontend-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "dev"
  - target:
      kind: Secret
      name: backend-secret
    patch: |
      - op: replace
        path: /data/ADMIN_PASSWORD
        value: c2VjcmV0LWZvci1kZXY=
