---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: dev
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCH7GQGbk2K1bmp+A4da+SX7FUKZwRsrceErxVENK8gHMwnFLgAxGC72yFzal6pj2DG2rZb5ahswiYUbchS8VBHhDI6l0MLD30iTtxFThhcZ54AsBaM9nZVT7inCy3+JgtslOyGpzeA+YgKsgLH95J92tl/9N7WRZzRA8GXEY4D3l+MVeBAMe/MUF6NcwvhaV/pfk15MhNfDuQiwW4XhDfbdzHmFK38f9qXWzKy76uCDwjWUaALiNF0VrhKx+oCww21mruuMpaOx9ORV/dqV9aGT7i/9BTAE5UpnNSg8zv6k273nc+3GATjpk5SyHxJ+uTOw0AODdjprwDr3nH//+DLz+pxL5JJ/1/m19P565i6UBiHlFC+j+PA9Hav/mbDzrye5FaDOAWbrv9mrHRUnRCGsQyftGNlL435Eso6XRh5EOmAxW2qTG3QEmrDknVKoejbhEV9dbZFXIacDUGdLmhT6SoJtrPRguJWhsNL2NHtOxlThnihD85KBEEsh89hreO3D40yMvaKhq0dpEERBb1zKz6x9v1J+hGoW8OQAxX9nNfMp4gSwrTge4oW0WJp1faLBRQVO9ooZ7UP+dXyrtjFyRg2yCjuRczW04DEbU3vBw9sD0ivxHVtW27B6+xpyVMgbJN6ZHv01IyU34R+w5l0Z2nE9x1sZ14FZLTOGl1TfWyvpWY/umEGfH8wL3+sCZCzvPH7OjjbVjwtVjNfD/AliUgIhQ==
    API_KEY: AgBhdONsstVdYRkaOIeoKjmZ5tSWHYNrfCIhNmHbmxuhgFy81NRskjw/hblen3fezd11ytT+8TrM8hbG+WP/i1Y+UN2tTWM9yUIiVumC8uvZG99CGfFMf3DQNYRQuJxy69WZFFmKpa6l1pM99HwFGIvIo/iAbFvkIt9rFE/esca20uyhXyO6DjfuLdQ+HGiDnlwE0TxaO3KeeKZ6S8Zbs54k/qhCrAnncCHi4mXn2W7c3JN07kNPuCzhjuVlwgj5kJuQKfskNXM4zTXZQNBlbqXrC1OA4R49O+MM49t201HIJWsymVBifezZc0wBtkG+eVzoYZAKR6pKV5AlfodtqSkGlSi1HJJ8PnZ5Iso8lvLZMKxkWpn2b6tl7QXKlyxkBfLmYwwTljyl5SyWo657aYvCM4npf4dkvqL0umPnh2Vt/5YdH3gTwZLRufNZHkaiZYEcXP6wbpCbGD7kgPvWuNWIkyN2IoW5H8dNE9cWd6mnKZhO3M8ETePuQPWQ8TsqXcYVwj2JCBallnPR21gjwhlW52xQegtWN3wQOawDjBzzCcmpXB6GLQEVGjuV5VOREALONZ/r5CROfFDnXfJ0gShiUTIqtUq517t2Amx9lGDUFJ5peIWlUJBu/6MeTtek/vOczKbEmP90sZsFZnHBmGB0JQc6QrMNCajCdOzuJoFYjmVvsOZc2GLD3Y5BeXc38SYhyk36YOu7lWJG/k8V/uiT
  template:
    metadata:
      name: backend-secrets
      namespace: dev
    type: Opaque
